server:
  port: 8050
spring:
  application:
    name: ms-file-upload
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2500Mb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true