server:
  port: 8040
spring:
  application:
    name: ms-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
#  prefix: /api
#  strip-prefix: false
  routes:
    ms-provider-user: /user/**
logging:
  level:
    com.netflix: debug
#zuul:
#  sensitive-headers: Cookie,Set-Cookie,Authorization  # 默认
#  ignored-headers: Header1,Header2
#zuul:
#  routes:
#    ms-provider-user:
#      path: /user/**
#      sensitive-headers: Cookie,Set-Cookie,Authorization
#      url: http://localhost:8010

#zuul路由规则详解
#1.自定义指定微服务的访问路径
#zuul:
#  routes:
#    ms-provider-user: /user/**
#  ignored-services:
##  ignored-services: ms-provider-user,ms-consumer-movie

#zuul:
#  routes:
#    user-route:
#      path: /user/**
#      service-id: ms-provider-user

#zuul:
#  routes:
#    user-route:
#      path: /user/**
#      url: http://localhost:8010/

#zuul:
#  routes:
#    user-route:
#      path: /user/**
#      service-id: ms-provider-user
#ribbon.eureka.enabled: false
#ms-provider-user:
#  ribbion:
#    listOfServers: http://localhostt:8000,httpt://localhost:8001